# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f758469b65173ecaf2e5c0358f4c803c62a92f4b0ff5ec30534dc35841a4a627ecdef058c358ada6af570e45cd257f1dcf16f7be6c5baa91d5f06ad2b372edc

test:
  secret_key_base: 28d1ae3bdab9679d3940ace60f8d45cd87123c8f937cd9e7fe1de8caaabea5aeec69e212d3146e2ebdc4243e78ed3a722d97723e1e8ea0192ade7daffd745630

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
